name: Check
'on': push
jobs:
  build:
    name: covr
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
      - name: Install Package Dependencies
        run: |-
          Rscript -e "install.packages(c('rcmdcheck', 'remotes', 'covr'), repos = 'https://demo.rstudiopm.com/all/__linux__/focal/latest')"
          Rscript -e "remotes::install_deps(dependencies = TRUE, repos = 'https://demo.rstudiopm.com/all/__linux__/focal/latest')"
      - name: codecov
        run: Rscript -e "covr::codecov(quiet = FALSE)"
    container: rocker/verse:latest
  rcmdchecker:
    name: Rcmdcheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
      - name: Install Package Dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check
      - name: Run Check
        uses: r-lib/actions/check-r-package@v2
    container: rocker/verse:latest
  rchk:
    runs-on: ubuntu-latest
    container:
      image: rhub/ubuntu-rchk
      options: --user=root
    steps:
    - uses: actions/checkout@v2
    - uses: r-lib/actions/setup-r@v2
    - name: pre-install
      run: Rscript -e "install.packages('glue')"
    - uses: r-lib/actions/run-rchk@v2
  test-r-sanitizers:
    name: ASAN-UBSAN
    timeout-minutes: 60
    runs-on: ubuntu-latest
    container:
      image: rhub/rocker-gcc-san
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
        with:
          fetch-depth: 5
          submodules: true
      - name: Install packages
        shell: bash
        run: |
          Rdevel -q -e "install.packages(c('fy', 'tinytest'))"
          Rdevel CMD build .
          Rdevel CMD INSTALL --install-tests *.tar.gz
          Rdevel -q -e "tinytest::test_all()"
